/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const QwikCityProvider: typeof import('@builder.io/qwik-city')['QwikCityProvider']
  const RouterOutlet: typeof import('@builder.io/qwik-city')['RouterOutlet']
  const ServiceWorkerRegister: typeof import('@builder.io/qwik-city')['ServiceWorkerRegister']
  const Slot: typeof import('@builder.io/qwik')['Slot']
  const noSerialize: typeof import('@builder.io/qwik')['noSerialize']
  const routeLoader$: typeof import('@builder.io/qwik-city')['routeLoader$']
  const useDocumentHead: typeof import('@builder.io/qwik-city')['useDocumentHead']
  const useLocation: typeof import('@builder.io/qwik-city')['useLocation']
  const useOnWindow: typeof import('@builder.io/qwik')['useOnWindow']
  const useSignal: typeof import('@builder.io/qwik')['useSignal']
  const useStore: typeof import('@builder.io/qwik')['useStore']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { NoSerialize, Signal, JSXNode } from '@builder.io/qwik'
  // @ts-ignore
  export type { DocumentHead } from '@builder.io/qwik-city'
}
