/**
 * Module contains theme variables.
 * @module src/shared/ui/styles/theme.css
 */
import { createTheme, createThemeContract } from '@vanilla-extract/css';
import { transparentize } from 'polished';

import { palette } from './palette.css';

export const theme = createThemeContract({
    background: {
        backdropShadow: null,
        content: null,
        contentAccent: null,
        dropdown: null,
        global: null,
        header: null,
        headerSolid: null,
        modalBackdropColor: null,
        overlay: null,
        overlayDark: null,
    },
    border: null,
    common: {
        alert: null,
        primary: null,
        secondary: null,
        tertiary: null,
        warning: null,
    },
    divider: null,
    primary: {
        button: null,
        buttonAccent: null,
        buttonAccentFillNone: null,
        buttonAccentOutlined: null,
        buttonDisabled: null,
        buttonText: null,
        buttonTextAccent: null,
        buttonTextOutlined: null,
        link: null,
        linkAccent: null,
        linkDisabled: null,
        linkText: null,
        linkTextAccent: null,
        linkTextDisabled: null,
        text: null,
        textField: null,
        textFieldAccent: null,
        textFieldAccentOutlined: null,
        textFieldLabel: null,
    },
    secondary: {
        button: null,
        buttonAccent: null,
        buttonAccentFillNone: null,
        buttonAccentOutlined: null,
        buttonDisabled: null,
        buttonText: null,
        buttonTextAccent: null,
        buttonTextOutlined: null,
        link: null,
        linkAccent: null,
        linkDisabled: null,
        linkText: null,
        linkTextAccent: null,
        linkTextDisabled: null,
        text: null,
        textField: null,
        textFieldAccent: null,
        textFieldAccentOutlined: null,
        textFieldLabel: null,
    },
    shadow: {
        modal: null,
        normal: null,
        text: null,
        textBold: null,
    },
    tertiary: {
        button: null,
        buttonAccent: null,
        buttonAccentFillNone: null,
        buttonAccentOutlined: null,
        buttonDisabled: null,
        buttonText: null,
        buttonTextAccent: null,
        buttonTextOutlined: null,
        link: null,
        linkAccent: null,
        linkDisabled: null,
        linkText: null,
        linkTextAccent: null,
        linkTextDisabled: null,
        text: null,
        textField: null,
        textFieldAccent: null,
        textFieldAccentOutlined: null,
        textFieldLabel: null,
    },
});

/* eslint-disable @typescript-eslint/no-magic-numbers */

export const dark = createTheme(theme, {
    background: {
        backdropShadow: `radial-gradient(
            ellipse at center,
            ${transparentize(0.5, palette.black)} 0,
            ${transparentize(0.8, palette.black)} 45%,
            ${transparentize(0.9, palette.black)} 55%,
            transparent 70%
        );`,
        content: palette['grey-900'],
        contentAccent: palette['grey-50'],
        dropdown: transparentize(0.3, palette['grey-1200']),
        'global': palette['grey-950'],
        header: `linear-gradient(
            180deg,
            ${transparentize(0.3, palette.black)} 10%,
            transparent
        );`,
        headerSolid: transparentize(0.1, palette['grey-1200']),
        modalBackdropColor: 'rgba(13, 28, 46, 0.4)',
        overlay: transparentize(0.18, palette.black),
        overlayDark: transparentize(0.05, palette.black),
    },
    border: palette['grey-850'],
    common: {
        alert: palette['red-650'],
        primary: palette['red-650'],
        secondary: palette['lime-a700'],
        tertiary: palette['grey-50'],
        warning: palette['orange-800'],
    },
    divider: palette['grey-800'],
    primary: {
        button: palette['red-650'],
        buttonAccent: transparentize(0.2, palette['red-650']),
        buttonAccentFillNone: transparentize(0.1, palette['red-650']),
        buttonAccentOutlined: transparentize(0.15, palette['red-650']),
        buttonDisabled: palette['red-700'],
        buttonText: palette.white,
        buttonTextAccent: palette.white,
        buttonTextOutlined: palette.white,
        link: palette['grey-550'],
        linkAccent: palette['grey-100'],
        linkDisabled: palette['grey-700'],
        linkText: palette['grey-400'],
        linkTextAccent: palette['grey-50'],
        linkTextDisabled: palette['grey-700'],
        text: palette['grey-100'],
        textField: palette['grey-800'],
        textFieldAccent: palette['grey-700'],
        textFieldAccentOutlined: palette['grey-100'],
        textFieldLabel: palette['grey-500'],
    },
    secondary: {
        button: transparentize(0.15, palette['grey-100']),
        buttonAccent: transparentize(0.05, palette['grey-100']),
        buttonAccentFillNone: transparentize(0.1, palette['grey-100']),
        buttonAccentOutlined: transparentize(0.15, palette['grey-100']),
        buttonDisabled: palette['grey-500'],
        buttonText: palette.black,
        buttonTextAccent: palette.black,
        buttonTextOutlined: palette.black,
        link: palette['grey-550'],
        linkAccent: transparentize(0.2, palette['grey-100']),
        linkDisabled: palette['grey-500'],
        linkText: palette['grey-350'],
        linkTextAccent: transparentize(0.2, palette['grey-350']),
        linkTextDisabled: palette['grey-500'],
        text: palette.black,
        textField: palette['grey-800'],
        textFieldAccent: palette['grey-700'],
        textFieldAccentOutlined: palette['grey-100'],
        textFieldLabel: palette['grey-500'],
    },
    shadow: {
        modal: '0 4px 20px rgba(66, 69, 115, 0.3)',
        normal: '0 2px 10px rgba(136, 154, 201, 0.3)',
        text: `0 1px 2px ${transparentize(0.4, palette.black)}`,
        textBold: `2px 2px 4px ${transparentize(0.6, palette.black)}`,
    },
    tertiary: {
        button: transparentize(0.15, palette['grey-550']),
        buttonAccent: transparentize(0.2, palette['grey-550']),
        buttonAccentFillNone: transparentize(0.1, palette['grey-550']),
        buttonAccentOutlined: transparentize(0.13, palette['grey-300']),
        buttonDisabled: palette['grey-500'],
        buttonText: palette.white,
        buttonTextAccent: transparentize(0.05, palette['grey-300']),
        buttonTextOutlined: palette['grey-550'],
        link: palette['grey-550'],
        linkAccent: transparentize(0.8, palette['grey-550']),
        linkDisabled: palette['grey-500'],
        linkText: palette['grey-550'],
        linkTextAccent: transparentize(0.2, palette['grey-550']),
        linkTextDisabled: palette.black,
        text: palette['grey-600'],
        textField: palette['grey-800'],
        textFieldAccent: palette['grey-700'],
        textFieldAccentOutlined: palette['grey-100'],
        textFieldLabel: palette['grey-500'],
    },
});
